name: Deploy service
on: [ push ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.0
      - name: Install poetry
        run: python -m pip install
      - name: Install dependencies
        run: make .venv
      - name: Lint the project
        run: make lint