name: Deploy livecoding.marnikitta.com
concurrency: production
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.0
      - name: Install poetry
        run: python -m pip install poetry
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Build the project
        run: make build
      - name: Lint the project
        run: make lint
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/deployment.key
          chmod 600 ~/.ssh/deployment.key
          cat >>~/.ssh/config <<END
          Host livecoding
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/deployment.key
            StrictHostKeyChecking no
            Port 2222
          END
        env:
          SSH_USER: ${{ secrets.deployment_ssh_user }}
          SSH_KEY: ${{ secrets.deployment_ssh_key }}
          SSH_HOST: ${{ secrets.deployment_ssh_host }}
      - name: Deploy
        run: make deploy
